### ISSUE TITLE
Releasing a new version with the latest changes from master

### ISSUE THREAD

**Issue by paulrbr-fl** [trainline-eu/ansible-postgresql-role#5]
Hi @chtitux,

would you mind cutting a new release with the latest PR merged into master please :pray: 
Thank you very much 🙂

**Comment by chtitux** [comment]
Can't you do it yourself ?

I think it will be easier :-) 

If you can't, please tell me, I'll grant you !

**Comment by paulrbr-fl** [comment]
Indeed I am able to do so. 

**1.3.0 released** then https://github.com/trainline-eu/ansible-postgresql-role/releases/tag/1.3.0

Sorry for the noise!
