### ISSUE TITLE
Getting it up and running

### ISSUE THREAD

**Issue by ghost** [trainline-eu/ansible-postgresql-role#7]
The ansible role, together with its additional barman role, doesn't seem to get going by themselves after the playbook is done.

After successfully creating a four servers: barman, primary, 2x secondary, I need to login to the primary and restart the postgresql service to get it to run according to the configurations set by the ansible role.

If I try the same thing on the secondaries, I first have to add their public keys as authorized keys on the barman server to get the rsync command to work, but I still don't get automatic streaming from the primary down to the secondaries.

This is all done on ubuntu machines, where I also have to change the `become_method` calls in the tasks to `sudo` to get it to work (or just comment them out).

Are there any pointers on how to get the first machines going correctly?

**Comment by paulRbr** [comment]
Hi @patrickstrang, thanks for sharing your experience with the role !

There is indeed a small set of manual actions left to do for first setup.

I have tried to get a cluster running smoothly in the test/main.yml test
case bit its not fully automated yet :)

If I have time I'll take a look at this soon.

**Comment by ghost** [comment]
Great. Thanks.

I will fork the project and add the things we did to get it up and running, and that might render a PR.

**Comment by chtitux** [comment]
@patrickstrang If you still have issue with the role, feel free to reopen the issue, I'll close it for now.
